### ISSUE TITLE
Receiving "An exception occured: Cannot send a content-body with this verb-type" running cmdlets

### ISSUE THREAD

**Issue by bryanmillerhk** [kayasax/EasyPIM#12]
When running the cmdlets, I'm receiving the following:

```
An exception occured: Cannot send a content-body with this verb-type.

Details:
Position: At C:\Program Files\WindowsPowerShell\Modules\EasyPIM\1.1.0\EasyPIM.psm1:391 char:21
+ ... $response = Invoke-RestMethod -Uri $restUri -Method $method -Headers  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error, script did not terminate normaly
```
Example command:

`Export-PIMAzureResourcePolicy -TenantID <redacted> -SubscriptionId <redacted> -rolename "webmaster","contributor" -exportFilename "C:\temp\roles.csv"`

**Comment by kayasax** [comment]
Hi @bryanmillerhk tahnk you for reporting this. I think I found the issue, should be fixed in the next version (maybe next week)
