### ISSUE TITLE
Code issue on $scope for New-PIMAzureResourceActiveAssignment Remove-PIMAzureResourceActiveAssignment New-PIMAzureResourceEligibleAssignment Remove-PIMAzureResourceEligibleAssignment

### ISSUE THREAD

**Issue by limjianan** [kayasax/EasyPIM#16]
My issues

Details: {"error":{"code":"InvalidAuthenticationTokenTenant","message":"The access token is from the wrong issuer 'https://sts.windows.net/d7c06050-84c6-4017-8d95-ae3783263046/'. It must match one of the tenants 'https://sts.windows.net/8d4fd732-58aa-4643-8cae-974854a66a2d/,https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/' associated with this subscription. Please use any authority (URL) from 'https://login.windows.net/8d4fd732-58aa-4643-8cae-974854a66a2d,https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."}}
Position: At C:\Program Files\WindowsPowerShell\Modules\EasyPIM\1.2.1\EasyPIM.psm1:395 char:25

i review the code and think some code issue as below

on https://github.com/kayasax/EasyPIM/blob/main/EasyPIM/functions/New-PIMAzureResourceActiveAssignment.ps1

Line 92 set up to $scope 
but 
Line 97    $scope = "subscriptions/eedcaa84-3756-4da9-bf87-40068c3dd2a2" actually appears. it force me to not able to use this

this is the same on 
https://github.com/kayasax/EasyPIM/blob/main/EasyPIM/functions/New-PIMAzureResourceEligibleAssignment.ps1

Line 93 set up to the $scope
but Line 98 has reset it $scope = "subscriptions/eedcaa84-3756-4da9-bf87-40068c3dd2a2"

I believe the remove-* has the same issues

**Comment by kayasax** [comment]
Hello @limjianan you are totaly right, apologies for introducing this error, will try to correct it quick :)
Thank you very much for reporting this and your analysis
