### ISSUE TITLE
powershell v5 compatibility issue - get-date -astc

### ISSUE THREAD

**Issue by limjianan** [kayasax/EasyPIM#17]
get-date -astc is recently introduce to powershell 7.4

I am using Powershell v5 and that command got bomb out. 

I have to replace this $startDateTime = get-date (get-date).touniversaltime() -f "yyyy-MM-ddTHH:mm:ssZ"

I am fine with this but it is good to call out your code is build on 7.4 or make backward compatible: :)

I replace the code with the below.

    if ($PSBoundParameters.Keys.Contains('startDateTime')) {
        $startDateTime = get-date ([datetime]::Parse($startDateTime)).touniversaltime() -f "yyyy-MM-ddTHH:mm:ssZ"
    }
    else {
        $startDateTime = get-date (get-date).touniversaltime() -f "yyyy-MM-ddTHH:mm:ssZ" #we get the date as UTC (remember to add a Z at the end or it will be translated to US timezone on import)
    }

**Comment by kayasax** [comment]
@limjianan another great catch 👍 thank you

**Comment by limjianan** [comment]
you might want to correct all 4 script (the new and remove) 
your fix #17 only highlight 1 place
