### ISSUE TITLE
New-PIMAzureResourceActiveAssignment must use subscription even though scope is specified. 

### ISSUE THREAD

**Issue by limjianan** [kayasax/EasyPIM#20]
When i run 

New-PIMAzureResourceActiveAssignment -tenantID $context.Tenant.id -scope $rg.ResourceId -rolename $role -principalID $g.id -justification 'part of scripts' -permanent

it provides error message 
of 
New-PIMAzureResourceActiveAssignment : Cannot bind argument to parameter 'subscriptionID' because it is an empty string.
At line:1 char:1
+ New-PIMAzureResourceActiveAssignment -tenantID $context.Tenant.id -sc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-PIMAzureResourceActiveAssignment], ParameterBindingValidationExcepti
   on
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-PIMAzureResourceActiveAssignment

The easy fix is to put the -subscriptionid in the command, 
this is not the same as the get command; you can just use the scope without licence. 

for example, 
get-pimazureresourceActiveAssignment -scope $rg.ResourceId -tenantID $context.Tenant.id  

This will return the result without the use of -subscriptionid

**Comment by kayasax** [comment]
@limjianan I would love to have your feedback regarding this module, please use the  contact owner link from the gallery to get in touch if you want https://www.powershellgallery.com/packages/EasyPIM/1.2.3/ContactOwners
