### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by limjianan** [kayasax/EasyPIM#22]
Sometimes, when you try to assign the group,  New-PIMAzureResourceEligibleAssignment or New-PIMAzureResourcepermenantAssignment
An exception occured: The remote server returned an error: (400) Bad Request.

Details: {"error":{"code":"SubjectNotFound","message":"The subject is not found."}}
Position: At C:\Program Files\WindowsPowerShell\Modules\EasyPIM\1.2.1\EasyPIM.psm1:392 char:25
+ ... $response = Invoke-RestMethod -Uri $restUri -Method $method -Headers  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error, script did not terminate normaly

The code is normal when the group was created, but some how not yet reflect in the system; 
sometimes it take 5 sec, sometimes it take 15 sec, and sometimes is takes more than 30 sec. 

wishful, is when there is an error, at least retry 3 times for that consequence before it throw the error message.

for me, at the moment, i just rerun it again the next time, usually it fixed it self :)

**Comment by kayasax** [comment]
We could use this graph query to validate the existence of the ObjectID https://learn.microsoft.com/en-us/graph/api/directoryobject-get?view=graph-rest-1.0&tabs=http , 
yet this will introduce the need to connect to graph, having the correct permission and delays.
I would say this is more the user responsibility to ensure the principal exist before calling the function, but I'm open to discussion...

**Comment by sfaizi90** [comment]
@kayasax thanks for the great function firstly. I am getting an error when running the Set-PIMAzureResourcePolicy  command:

An exception occured: Response status code does not indicate success: 400 (Bad Request).                                

Details:
{
  "error": {
    "code": "InvalidPolicy",
    "message": "The policy is invalid."
  }
}

New-PIMAzureResourceEligibleAssignment  command works fine. Any thoughts on what policy is blocking this? As far as i could check there's no policy i could find to block this. Please advise.

**Comment by kayasax** [comment]
Hello @sfaizi90  can you share the complete command you have used?
You may also have a look a the audit log if it can provide more information : https://portal.azure.com/#view/Microsoft_Azure_PIMCommon/MyAuditsMenuBlade/~/azurerbac

Another option that could help to troubleshoot is to run your command with the -verbose switch.

**Comment by sfaizi90** [comment]
Thanks for the quick response.

When command to setup approvers, i get the policy error.

Set-PIMAzureResourcePolicy -TenantID $tenantID -subscriptionID
$subscriptionId -rolename $roleName -ActivationRequirement
$ActivationRequirement -AllowPermanentEligibility $true  -ApprovalRequired
$true -Approvers @(@{"Id"="d24c4b8e-b106-401d-bb61-8dxcxa07588c";
"Name"="king]"; "Type"="user"}) -Verbose

output:

ERBOSE:  #1 Get role definition for the role ARO-Costco-Cloud Custom
Contributor assignable at the scope
subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd at
https://management.azure.com/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleDefinitions?api-version=2022-04-01&$filter=roleName
eq 'ARO-Costco-Cloud Custom Contributor'
VERBOSE:
>> request body:
VERBOSE: request URI :
https://management.azure.com/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleDefinitions?api-version=2022-04-01&$filter=roleName
eq 'ARO-Costco-Cloud Custom Contributor'
VERBOSE: >> Getting access token
VERBOSE: >> RodeId =
/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleDefinitions/f6630eef-f3ab-40ac-bdc4-dd2b7193f809
VERBOSE:  #2 Get the Assignment for ARO-Costco-Cloud Custom Contributor at
https://management.azure.com/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleManagementPolicyAssignments?api-version=2020-10-01&$filter=roleDefinitionId
eq
'/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleDefinitions/f6630eef-f3ab-40ac-bdc4-dd2b7193f809'
VERBOSE:
>> request body:
VERBOSE: request URI :
https://management.azure.com/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleManagementPolicyAssignments?api-version=2020-10-01&$filter=roleDefinitionId
eq
'/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleDefinitions/f6630eef-f3ab-40ac-bdc4-dd2b7193f809'
VERBOSE: >> Getting access token
VERBOSE: >> policy ID =
/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleManagementPolicies/b43045b6-5fa5-4210-ad28-ddb6d7967a3c
VERBOSE:  #3 get role policy at
https://management.azure.com//subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleManagementPolicies/b43045b6-5fa5-4210-ad28-ddb6d7967a3c/?api-version=2020-10-01
VERBOSE:
>> request body:
VERBOSE: request URI :
https://management.azure.com//subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleManagementPolicies/b43045b6-5fa5-4210-ad28-ddb6d7967a3c/?api-version=2020-10-01
VERBOSE: >> Getting access token
VERBOSE: Set-Approval
VERBOSE: Performing the operation "Udpdating policy" on target "Custom
Contributor".
VERBOSE:
>> request body:
        {
            "properties": {
            "scope": "subscriptions/cdba4838-0335-49c9-8c67-8641dbe28244",
            "rules": [

    {
        "setting": {"isApprovalRequired": true,
        "isApprovalRequiredForExtension": false,
        "isRequestorJustificationRequired": true,
        "approvalMode": "SingleStage",
        "approvalStages": [
            {
            "approvalStageTimeOutInDays": 1,
            "isApproverJustificationRequired": true,
            "escalationTimeInMinutes": 0,

            "primaryApprovers": [

            {
                "id": "d24c4b8e-b106-401d-bb61-8def9a07588c",
                "description": "king]",
                "isBackup": false,
                "userType": "user"
            }

            ],
        "isEscalationEnabled": false,
            "escalationApprovers": null
                    }]
                 },
        "id": "Approval_EndUser_Assignment",
        "ruleType": "RoleManagementPolicyApprovalRule",
        "target": {
            "caller": "EndUser",
            "operations": [
                "All"
            ],
            "level": "Assignment",
            "targetObjects": null

            },


            "inheritableSettings": null,
            "enforcedSettings": null

        }}],
          "level": "Assignment"
            }
        }
VERBOSE: request URI :
https://management.azure.com//subscriptions/cdba4838-0335-49c9-8c67-8041dbe28255/providers/Microsoft.Authorization/roleManagementPolicies/b43045b6-5fa5-4210-ad28-ddb6d7967a3c/?api-version=2020-10-01
VERBOSE: >> Getting access token
An exception occured: Response status code does not indicate success: 400
(Bad Request).

Details:
{
  "error": {
    "code": "InvalidPolicy",
    "message": "The policy is invalid."
  }
}
Position: At
C:\Users\skhan\Documents\PowerShell\Modules\easypim\1.5.0\EasyPIM.psm1:853
char:25
+ … $response = Invoke-RestMethod -Uri $restUri -Method $method -Headers  …
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

On Thu, Mar 14, 2024 at 1:53 PM Loïc MICHEL ***@***.***>
wrote:

> Hello @sfaizi90
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sfaizi90&d=DwMCaQ&c=pApUd0AUA6FmKRo01iR_VA&r=72P7tmqKAJiXx9yWGJmHQ4NBqLfpmrNtGmZlq6kaI8I&m=PSpkqwAORpFRDpnKTuTSCvtHlgv6whyVzRdH4rKcuxBxSiG4jzrdQlCr7do_UkKs&s=ZbJTavCQQysFDY2M3H8O8Dt3rbiD0ZfMY0sWLzgFNU0&e=>
> can you share the complete command you have used?
> You may also have a look a the audit log if it can provide more
> information :
> https://portal.azure.com/#view/Microsoft_Azure_PIMCommon/MyAuditsMenuBlade/~/azurerbac
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__portal.azure.com_-23view_Microsoft-5FAzure-5FPIMCommon_MyAuditsMenuBlade_-7E_azurerbac&d=DwMCaQ&c=pApUd0AUA6FmKRo01iR_VA&r=72P7tmqKAJiXx9yWGJmHQ4NBqLfpmrNtGmZlq6kaI8I&m=PSpkqwAORpFRDpnKTuTSCvtHlgv6whyVzRdH4rKcuxBxSiG4jzrdQlCr7do_UkKs&s=7ze-GFFaKlX9z38NkfmN9W5g38xNHG900MJHvApH0ho&e=>
>
> Another option that could help to troubleshoot is to run your command with
> the -verbose switch.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kayasax_EasyPIM_issues_22-23issuecomment-2D1998465477&d=DwMCaQ&c=pApUd0AUA6FmKRo01iR_VA&r=72P7tmqKAJiXx9yWGJmHQ4NBqLfpmrNtGmZlq6kaI8I&m=PSpkqwAORpFRDpnKTuTSCvtHlgv6whyVzRdH4rKcuxBxSiG4jzrdQlCr7do_UkKs&s=vfJnZldm77A12FbxF5yEFDEF-YpMDpX_JF4mqZD2lCM&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BGYT2EQFYDLCPBTTB4PBRLLYYIE27AVCNFSM6AAAAABDJFO2FWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOJYGQ3DKNBXG4&d=DwMCaQ&c=pApUd0AUA6FmKRo01iR_VA&r=72P7tmqKAJiXx9yWGJmHQ4NBqLfpmrNtGmZlq6kaI8I&m=PSpkqwAORpFRDpnKTuTSCvtHlgv6whyVzRdH4rKcuxBxSiG4jzrdQlCr7do_UkKs&s=M35fW0dCNrrByju-KxnI6NFoIKnXDky4LisLwgUwETI&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Regards,
Shafiq Faizi
Cloud Technologies

**Comment by sfaizi90** [comment]
Also, the failure of the command does not show on the Audit report in azure
portal.

On Thu, Mar 14, 2024 at 3:31 PM Shafiqullah Faizi ***@***.***> wrote:

> Thanks for the quick response.
>
> When command to setup approvers, i get the policy error.
>
> Set-PIMAzureResourcePolicy -TenantID $tenantID -subscriptionID
> $subscriptionId -rolename $roleName -ActivationRequirement
> $ActivationRequirement -AllowPermanentEligibility $true  -ApprovalRequired
> $true -Approvers @(@{"Id"="d24c4b8e-b106-401d-bb61-8dxcxa07588c";
> "Name"="king]"; "Type"="user"}) -Verbose
>
> output:
>
> ERBOSE:  #1 Get role definition for the role ARO-Costco-Cloud Custom
> Contributor assignable at the scope
> subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd at
> https://management.azure.com/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleDefinitions?api-version=2022-04-01&$filter=roleName
> eq 'ARO-Costco-Cloud Custom Contributor'
> VERBOSE:
> >> request body:
> VERBOSE: request URI :
> https://management.azure.com/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleDefinitions?api-version=2022-04-01&$filter=roleName
> eq 'ARO-Costco-Cloud Custom Contributor'
> VERBOSE: >> Getting access token
> VERBOSE: >> RodeId =
> /subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleDefinitions/f6630eef-f3ab-40ac-bdc4-dd2b7193f809
> VERBOSE:  #2 Get the Assignment for ARO-Costco-Cloud Custom Contributor at
> https://management.azure.com/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleManagementPolicyAssignments?api-version=2020-10-01&$filter=roleDefinitionId
> eq
> '/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleDefinitions/f6630eef-f3ab-40ac-bdc4-dd2b7193f809'
> VERBOSE:
> >> request body:
> VERBOSE: request URI :
> https://management.azure.com/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleManagementPolicyAssignments?api-version=2020-10-01&$filter=roleDefinitionId
> eq
> '/subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleDefinitions/f6630eef-f3ab-40ac-bdc4-dd2b7193f809'
> VERBOSE: >> Getting access token
> VERBOSE: >> policy ID =
> /subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleManagementPolicies/b43045b6-5fa5-4210-ad28-ddb6d7967a3c
> VERBOSE:  #3 get role policy at
> https://management.azure.com//subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleManagementPolicies/b43045b6-5fa5-4210-ad28-ddb6d7967a3c/?api-version=2020-10-01
> VERBOSE:
> >> request body:
> VERBOSE: request URI :
> https://management.azure.com//subscriptions/cdba4838-0335-49c9-8c67-8641dbe282dd/providers/Microsoft.Authorization/roleManagementPolicies/b43045b6-5fa5-4210-ad28-ddb6d7967a3c/?api-version=2020-10-01
> VERBOSE: >> Getting access token
> VERBOSE: Set-Approval
> VERBOSE: Performing the operation "Udpdating policy" on target "Custom
> Contributor".
> VERBOSE:
> >> request body:
>         {
>             "properties": {
>             "scope": "subscriptions/cdba4838-0335-49c9-8c67-8641dbe28244",
>             "rules": [
>
>     {
>         "setting": {"isApprovalRequired": true,
>         "isApprovalRequiredForExtension": false,
>         "isRequestorJustificationRequired": true,
>         "approvalMode": "SingleStage",
>         "approvalStages": [
>             {
>             "approvalStageTimeOutInDays": 1,
>             "isApproverJustificationRequired": true,
>             "escalationTimeInMinutes": 0,
>
>             "primaryApprovers": [
>
>             {
>                 "id": "d24c4b8e-b106-401d-bb61-8def9a07588c",
>                 "description": "king]",
>                 "isBackup": false,
>                 "userType": "user"
>             }
>
>             ],
>         "isEscalationEnabled": false,
>             "escalationApprovers": null
>                     }]
>                  },
>         "id": "Approval_EndUser_Assignment",
>         "ruleType": "RoleManagementPolicyApprovalRule",
>         "target": {
>             "caller": "EndUser",
>             "operations": [
>                 "All"
>             ],
>             "level": "Assignment",
>             "targetObjects": null
>
>             },
>
>
>             "inheritableSettings": null,
>             "enforcedSettings": null
>
>         }}],
>           "level": "Assignment"
>             }
>         }
> VERBOSE: request URI :
> https://management.azure.com//subscriptions/cdba4838-0335-49c9-8c67-8041dbe28255/providers/Microsoft.Authorization/roleManagementPolicies/b43045b6-5fa5-4210-ad28-ddb6d7967a3c/?api-version=2020-10-01
> VERBOSE: >> Getting access token
> An exception occured: Response status code does not indicate success: 400
> (Bad Request).
>
> Details:
> {
>   "error": {
>     "code": "InvalidPolicy",
>     "message": "The policy is invalid."
>   }
> }
> Position: At
> C:\Users\skhan\Documents\PowerShell\Modules\easypim\1.5.0\EasyPIM.psm1:853
> char:25
> + … $response = Invoke-RestMethod -Uri $restUri -Method $method -Headers  …
> +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>
> On Thu, Mar 14, 2024 at 1:53 PM Loïc MICHEL ***@***.***>
> wrote:
>
>> Hello @sfaizi90
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sfaizi90&d=DwMCaQ&c=pApUd0AUA6FmKRo01iR_VA&r=72P7tmqKAJiXx9yWGJmHQ4NBqLfpmrNtGmZlq6kaI8I&m=PSpkqwAORpFRDpnKTuTSCvtHlgv6whyVzRdH4rKcuxBxSiG4jzrdQlCr7do_UkKs&s=ZbJTavCQQysFDY2M3H8O8Dt3rbiD0ZfMY0sWLzgFNU0&e=>
>> can you share the complete command you have used?
>> You may also have a look a the audit log if it can provide more
>> information :
>> https://portal.azure.com/#view/Microsoft_Azure_PIMCommon/MyAuditsMenuBlade/~/azurerbac
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__portal.azure.com_-23view_Microsoft-5FAzure-5FPIMCommon_MyAuditsMenuBlade_-7E_azurerbac&d=DwMCaQ&c=pApUd0AUA6FmKRo01iR_VA&r=72P7tmqKAJiXx9yWGJmHQ4NBqLfpmrNtGmZlq6kaI8I&m=PSpkqwAORpFRDpnKTuTSCvtHlgv6whyVzRdH4rKcuxBxSiG4jzrdQlCr7do_UkKs&s=7ze-GFFaKlX9z38NkfmN9W5g38xNHG900MJHvApH0ho&e=>
>>
>> Another option that could help to troubleshoot is to run your command
>> with the -verbose switch.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kayasax_EasyPIM_issues_22-23issuecomment-2D1998465477&d=DwMCaQ&c=pApUd0AUA6FmKRo01iR_VA&r=72P7tmqKAJiXx9yWGJmHQ4NBqLfpmrNtGmZlq6kaI8I&m=PSpkqwAORpFRDpnKTuTSCvtHlgv6whyVzRdH4rKcuxBxSiG4jzrdQlCr7do_UkKs&s=vfJnZldm77A12FbxF5yEFDEF-YpMDpX_JF4mqZD2lCM&e=>,
>> or unsubscribe
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BGYT2EQFYDLCPBTTB4PBRLLYYIE27AVCNFSM6AAAAABDJFO2FWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOJYGQ3DKNBXG4&d=DwMCaQ&c=pApUd0AUA6FmKRo01iR_VA&r=72P7tmqKAJiXx9yWGJmHQ4NBqLfpmrNtGmZlq6kaI8I&m=PSpkqwAORpFRDpnKTuTSCvtHlgv6whyVzRdH4rKcuxBxSiG4jzrdQlCr7do_UkKs&s=M35fW0dCNrrByju-KxnI6NFoIKnXDky4LisLwgUwETI&e=>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>
>
> --
> Regards,
> Shafiq Faizi
> Cloud Technologies
>


-- 
Regards,
Shafiq Faizi
Cloud Technologies

**Comment by kayasax** [comment]
this is a bug with approvers/approval I created a new issue for this https://github.com/kayasax/EasyPIM/issues/28
