### ISSUE TITLE
[Bug] Membertype

### ISSUE THREAD

**Issue by limjianan** [kayasax/EasyPIM#23]
when run get-pimazureresourceActiveAssignment -tenantID $context.Tenant.id -subscriptionID $context.Subscription.id

Membertype is inaccurate when I have some inherited from management group. It shows the membertype is DIRECT when i know it is inherited from management group or ROOT.

**Comment by kayasax** [comment]
Unfortunately I cannot replicate this situation in my env. But I can tell you that EasyPIM does not manipulate this value, this is what we receive from the ARM API. Is this information different in Azure Portal?

**Comment by limjianan** [comment]
i spent a good time testing out and found it is a bug from Microsoft. 

if you add a group with time limit ( 6 months) on management group 
when run under subscription level, 
the REST API will always think it is DIRECT, but the UI will show up correctly as inherited

if you add a group without limit (permanent) on management group 
when run under subscription level, 
the REST API will always think it is DIRECT, but the UI will show up correctly as inherited


![image](https://github.com/kayasax/EasyPIM/assets/20926131/47e38710-d2f9-4462-a313-aa88052953aa)
![image](https://github.com/kayasax/EasyPIM/assets/20926131/e77f11b1-cffd-4005-ab78-b5962cb21d69)


and when i run get-pimazureresourceactiveAssignment -tenantID $context.Tenant.id -subscriptionID $context.Subscription.id | select membertype,principalname,principaltype,scopename,rolename,scopetype 

It shows up 
memberType    : Direct
PrincipalName : Sg-AZ-MG-Root-Contributor
PrincipalType : Group
ScopeName     : Tenant Root Group
RoleName      : Contributor
ScopeType     : managementgroup

memberType    : Direct
PrincipalName : Sg-AZ-MG-Root-Owner
PrincipalType : Group
ScopeName     : Tenant Root Group
RoleName      : Owner
ScopeType     : managementgroup

memberType    : Direct
PrincipalName : Sg-AZ-MG-Root-Reader
PrincipalType : Group
ScopeName     : Tenant Root Group
RoleName      : Reader
ScopeType     : managementgroup

memberType    : Inherited
PrincipalName : sg-IT
PrincipalType : Group
ScopeName     : Tenant Root Group
RoleName      : Role Based Access Control Administrator
ScopeType     : managementgroup

memberType    : Direct
PrincipalName : Sg-AZ-MG-Root-UserAccessAdministrator
PrincipalType : Group
ScopeName     : Tenant Root Group
RoleName      : User Access Administrator
ScopeType     : managementgroup

memberType    : Inherited
PrincipalName : MOD Administrator
PrincipalType : User
ScopeName     : /
RoleName      : User Access Administrator
ScopeType     : tenant

memberType    : Inherited
PrincipalName : MS-PIM
PrincipalType : ServicePrincipal
ScopeName     : Tenant Root Group
RoleName      : User Access Administrator
ScopeType     : managementgroup

memberType    : Direct
PrincipalName : sg-Retail
PrincipalType : Group
ScopeName     : Tenant Root Group
RoleName      : Virtual Machine Contributor
ScopeType     : managementgroup


I also pull directly from the API and found it has the same result as easyPIM.
I am not very sure Microsoft going to fix it as the 2022-04-01 command do not have the same command, OR 
the similar command https://management.azure.com/<$scope>/providers/Microsoft.Authorization/roleAssignments?api-version=2022-04-01 do not return membertype

**Comment by kayasax** [comment]
this is a bug with roleEligibilitySchedules API, we will use roleEligibilityScheduleInstances instead. The downside is that we wont be able to see assignments with a future start date.
