### ISSUE TITLE
Better message

### ISSUE THREAD

**Issue by limjianan** [kayasax/EasyPIM#24]
When Remove-PIMAzureResourceActiveAssignment OR Remove-PIMAzureResourceEligibleAssignment
message shows below 
SUCCESS : Assignment created!

It should be assignment removed :)

**Comment by kayasax** [comment]
Hi @limjianan, technically speaking we don't remove the assignment, we create a new one that invalidate the other. But I agree it will be better to have the message aligned with the cmdlet name :)
