### ISSUE TITLE
Entra Role Assignments Not Consistently Applying

### ISSUE THREAD

**Issue by rdbartram** [kayasax/EasyPIM#39]
I have an issue that when I assign the permission it isn't active...that is to say it appears under pending requests, with a request status of granted.

Seems very strange, if I remove it and apply again, sometimes it works and sometimes it doesn't. I thought maybe it was a replication, timing thing but I left it over night and it was still the same.

  
![image](https://github.com/kayasax/EasyPIM/assets/16256546/b2dea374-35e8-4823-8919-892f87ca615b)

**Comment by kayasax** [comment]
Hum this one will be hard to debug 😕 
I have seen this during my dev while trying ro assign a role  to a non role-assignable group, but easypim should be taking care of this now.
Did you notice any common pattern for these failed actions? Any useful info in the audit logs?

**Comment by kayasax** [comment]
closing this one as there is no update since 3weeks
