### ISSUE TITLE
Azure assigning at the management group scope

### ISSUE THREAD

**Issue by davidjhole** [kayasax/EasyPIM#55]
Hello, I can see you added support for scope and say it supports management group, can you let me know the format to pass in as I can't seem to find a way for it to work when using Set-PIMAzureResourcePolicy.
Thanks

**Comment by kayasax** [comment]
Hi @davidjhole thanks for using EasyPIM.

You can find an example for the syntax here: https://learn.microsoft.com/en-us/rest/api/authorization/privileged-role-eligibility-rest-sample#list-eligible-assignments

exemple for management group named MG1:

```powershell
$scope="providers/Microsoft.Management/managementGroups/MG1"
Set-PIMAzureResourcePolicy -TenantID $tenantID -scope $scope -rolename "reader" -AuthenticationContext_Enabled $true -AuthenticationContext_Value "c1" 
```
