### ISSUE TITLE
Typo in the Wiki

### ISSUE THREAD

**Issue by davidjhole** [kayasax/EasyPIM#57]
Page https://github.com/kayasax/EasyPIM/wiki/New%E2%80%90PIMAzureResourceActiveAssignment

There is a typo on both of the commands
`New-PIMAzureResourceActiveAssigment`
should be 
`New-PIMAzureResourceActiveAssignment`

**Comment by davidjhole** [comment]
this is the same https://github.com/kayasax/EasyPIM/wiki/New%E2%80%90PIMAzureResourceEligibleAssigment

**Comment by kayasax** [comment]
Thanks David!
