### ISSUE TITLE
An exception occured: Property "enabledRules" cannot be found.

### ISSUE THREAD

**Issue by vit-corp** [kayasax/EasyPIM#59]
Hi, 

Every time when i run the script i catch this error. 
Could you assist please?
![image](https://github.com/user-attachments/assets/60ae4413-7bd6-460e-a95d-f2a1b7c02cde)

**Comment by kayasax** [comment]
Hi, @vit-corp 
can you please run the same command with the `-verbose` switch and share the output?

**Comment by vit-corp** [comment]
Hi, @kayasax 
![image](https://github.com/user-attachments/assets/cccea76f-208a-4650-baa0-51ddbe23bd88)

**Comment by kayasax** [comment]
Sorry for the troubles, this seems to be an issue when using PowerShell 5,
I'm out of office this week, as a workaround please try to use PowerShell 7.
