### ISSUE TITLE
Error: InputPolicyNotFound when using EasyPIM module 16.6

### ISSUE THREAD

**Issue by Mansars** [kayasax/EasyPIM#60]
**Description**
An error occurs when using the EasyPIM module to retrieve policies. The specific error message is `{"error":{"code":"InputPolicyNotFound","message":"Policy is not found."}}`.

**To Reproduce**
1. Run the following PowerShell command:

Connect-azaccount

#Parameters
$tenantID = "TenantID"
$subscriptionId = "SubID"
$path = "C:\Users\User.Name\Dcuments\CoolPowershellScriptsFoPIM\PIMRolesToSort.csv"

Set-AzContext $subscriptionId

Import-PIMAzureResourcePolicy -TenantID $tenantID -path $path

**Error Details**
_An exception occurred: The remote server returned an error: (400) Bad Request.

Details: {"error":{"code":"InputPolicyNotFound","message":"Policy is not found."}}
Position: At C:\Program Files\WindowsPowerShell\Modules\EasyPIM\1.6.6\EasyPIM.psm1:894 char:25
+ ... $response = Invoke-RestMethod -Uri $restUri -Method $method -Headers  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Details:  
Position: At C:\Program Files\WindowsPowerShell\Modules\EasyPIM\1.6.6\EasyPIM.psm1:1127 char:5
+     throw "Error, script did not terminate gracefuly" #fix issue #40
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error, script did not terminate gracefuly
At C:\Program Files\WindowsPowerShell\Modules\EasyPIM\1.6.6\EasyPIM.psm1:1127 char:5
+     throw "Error, script did not terminate gracefuly" #fix issue #40
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error, script d...inate gracefuly:String) [], RuntimeException
    + FullyQualifiedErrorId : Error, script did not terminate gracefuly_

**Script Section Causing the Issue**

function Get-AllPolicies {
  [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseSingularNouns", "")]
  [CmdletBinding()]
  param (
      [Parameter()]
      [string]
      $scope
  )
    
  $ARMhost = "https://management.azure.com"
  $ARMendpoint = "$ARMhost/$scope/providers/Microsoft.Authorization"
  $restUri = "$ARMendpoint/roleDefinitions?`$select=roleName&api-version=2022-04-01"

  write-verbose "Getting All Policies at $restUri"
  $response = Invoke-ARM -restURI $restUri -Method 'GET' -Body $null
  Write-Verbose $response
  $roles = $response | ForEach-Object {
      $_.value.properties.roleName
  }
  return $roles
}

Please let me know if you need more information or if there are any further steps I can take to help debug this issue, as this script and the others you have been invaluable and saved weeks of work.

**Comment by Mansars** [comment]
**Verbose**

VERBOSE: Importing settings from C:\Users\.csv
VERBOSE: Performing the operation "Importing policy from" on target "C:\Users\.csv".
Importing setting from C:\Users\.csv
VERBOSE: Editing Activation duration : PT8H
VERBOSE: Set-ActivationRequirement : 2
VERBOSE: requirement is NOT nul
VERBOSE: Set-ApprovalFromCSV
VERBOSE: Set-EligibilityAssignmentFromCSV: P365D TRUE
VERBOSE: 1 setting expire to : false
VERBOSE: Set-ActiveAssignmentFromCSV(P45D, TRUE)
VERBOSE: Set-Notification_EligibleAssignment_Alert(System.Collections.Hashtable)
VERBOSE: end function notif elligible alert
VERBOSE: Updating Policy /subscriptions/
VERBOSE: script:scope = /subscriptions/
VERBOSE: 
>> request body: 
        {
            "properties": {
            "scope": "/subscriptions/",
            "rules": [
        {
    "maximumDuration":  "PT8H",
    "id":  "Expiration_EndUser_Assignment",
    "ruleType":  "RoleManagementPolicyExpirationRule",
    "isExpirationRequired":  "true",
    "level":  "Assignment",
    "target":  {
                   "caller":  "EndUser",
                   "operations":  [
                                      "All"
                                  ]
               }
},{
                "enabledRules": ["MultiFactorAuthentication","Justification"],
                "id": "Enablement_EndUser_Assignment",
                "ruleType": "RoleManagementPolicyEnablementRule",
                "target": {
                    "caller": "EndUser",
                    "operations": [
                        "All"
                    ],
                    "level": "Assignment",
                    "targetObjects": [],
                    "inheritableSettings": [],
                    "enforcedSettings": []
                }
            },
        {
        "setting": {"isApprovalRequired":false,
        "isApprovalRequiredForExtension": false,
        "isRequestorJustificationRequired": true,
        "approvalMode": "SingleStage",
        "approvalStages": [
            {
            "approvalStageTimeOutInDays": 1,
            "isApproverJustificationRequired": true,
            "escalationTimeInMinutes": 0,
        
            "primaryApprovers": [
            
                {
                    "id": "",
                    "description": "",
                    "isBackup": false,
                    "userType": ""
                }
                
            ],
        "isEscalationEnabled": false,
            "escalationApprovers": null
                    }]
                 },
        "id": "Approval_EndUser_Assignment",
        "ruleType": "RoleManagementPolicyApprovalRule",
        "target": {
            "caller": "EndUser",
            "operations": [
                "All"
            ],
            "level": "Assignment",
            "targetObjects": null,
            "inheritableSettings": null,
            "enforcedSettings": null
        
        }},
        {
        "isExpirationRequired": false,
        "maximumDuration": "P365D",
        "id": "Expiration_Admin_Eligibility",
        "ruleType": "RoleManagementPolicyExpirationRule",
        "target": {
          "caller": "Admin",
          "operations": [
            "All"
          ],
          "level": "Eligibility",
          "targetObjects": null,
          "inheritableSettings": null,
          "enforcedSettings": null
        }
    }
    ,
        {
        "isExpirationRequired": false,
        "maximumDuration": "P45D",
        "id": "Expiration_Admin_Assignment",
        "ruleType": "RoleManagementPolicyExpirationRule",
        "target": {
        "caller": "Admin",
        "operations": [
            "All"
        ],
        "level": "Eligibility",
        "targetObjects": null,
        "inheritableSettings": null,
        "enforcedSettings": null
        }
        }
    ,
        {
        "notificationType": "Email",
        "recipientType": "Admin",
        "isDefaultRecipientsEnabled": true,
        "notificationLevel": "Critical",
        "notificationRecipients": [
        ""
        ],
        "id": "Notification_Admin_Admin_Eligibility",
        "ruleType": "RoleManagementPolicyNotificationRule",
        "target": {
        "caller": "Admin",
        "operations": [
            "All"
        ],
        "level": "Eligibility",
        "targetObjects": null,
        "inheritableSettings": null,
        "enforcedSettings": null
        }
        }
    ,
        {
        "notificationType": "Email",
        "recipientType": "Requestor",
        "isDefaultRecipientsEnabled": true,
        "notificationLevel": "Critical",
        "notificationRecipients": [
        "",
        ],
        "id": "Notification_Requestor_Admin_Eligibility",
        "ruleType": "RoleManagementPolicyNotificationRule",
        "target": {
        "caller": "Admin",
        "operations": [
            "All"
        ],
        "level": "Eligibility",
        "targetObjects": null,
        "inheritableSettings": null,
        "enforcedSettings": null
        }
        },
        {
        "notificationType": "Email",
        "recipientType": "Approver",
        "isDefaultRecipientsEnabled": true,
        "notificationLevel": "Critical",
        "notificationRecipients": [
        "",
        ],
        "id": "Notification_Approver_Admin_Eligibility",
        "ruleType": "RoleManagementPolicyNotificationRule",
        "target": {
        "caller": "Admin",
        "operations": [
            "All"
        ],
        "level": "Eligibility",
        "targetObjects": null,
        "inheritableSettings": null,
        "enforcedSettings": null
        }
        },
    {
    "notificationType": "Email",
    "recipientType": "Admin",
    "isDefaultRecipientsEnabled": true,
    "notificationLevel": "Critical",
    "notificationRecipients": [
    ""
    ],
    "id": "Notification_Admin_Admin_Assignment",
    "ruleType": "RoleManagementPolicyNotificationRule",
    "target": {
    "caller": "Admin",
    "operations": [
        "All"
    ],
    "level": "Eligibility",
    "targetObjects": null,
    "inheritableSettings": null,
    "enforcedSettings": null
    }
    }
    ,
                {
                "notificationType": "Email",
                "recipientType": "Requestor",
                "isDefaultRecipientsEnabled": true,
                "notificationLevel": "Critical",
                "notificationRecipients": [
                "",
                ],
                "id": "Notification_Requestor_Admin_Assignment",
                "ruleType": "RoleManagementPolicyNotificationRule",
                "target": {
                "caller": "Admin",
                "operations": [
                    "All"
                ],
                "level": "Eligibility",
                "targetObjects": null,
                "inheritableSettings": null,
                "enforcedSettings": null
                }
                }
                ,
        {
        "notificationType": "Email",
        "recipientType": "Approver",
        "isDefaultRecipientsEnabled": true,
        "notificationLevel": "Critical",
        "notificationRecipients": [
        "",
        ],
        "id": "Notification_Approver_Admin_Assignment",
        "ruleType": "RoleManagementPolicyNotificationRule",
        "target": {
        "caller": "Admin",
        "operations": [
            "All"
        ],
        "level": "Eligibility",
        "targetObjects": null,
        "inheritableSettings": null,
        "enforcedSettings": null
        }
        }
        ,
        {
        "notificationType": "Email",
        "recipientType": "Admin",
        "isDefaultRecipientsEnabled": true,
        "notificationLevel": "Critical",
        "notificationRecipients": [
        ""
        ],
        "id": "Notification_Admin_EndUser_Assignment",
        "ruleType": "RoleManagementPolicyNotificationRule",
        "target": {
        "caller": "Admin",
        "operations": [
            "All"
        ],
        "level": "Eligibility",
        "targetObjects": null,
        "inheritableSettings": null,
        "enforcedSettings": null
        }
        }
        ,
         {
         "notificationType": "Email",
         "recipientType": "Requestor",
         "isDefaultRecipientsEnabled": true,
         "notificationLevel": "All",
         "notificationRecipients": [
         "",
         ],
         "id": "Notification_Requestor_EndUser_Assignment",
         "ruleType": "RoleManagementPolicyNotificationRule",
         "target": {
         "caller": "Admin",
         "operations": [
             "All"
         ],
         "level": "Eligibility",
         "targetObjects": null,
         "inheritableSettings": null,
         "enforcedSettings": null
         }
         }
         ,
        {
        "notificationType": "Email",
        "recipientType": "Approver",
        "isDefaultRecipientsEnabled": true,
        "notificationLevel": "Critical",
        "notificationRecipients": [
        
        ],
        "id": "Notification_Approver_EndUser_Assignment",
        "ruleType": "RoleManagementPolicyNotificationRule",
        "target": {
        "caller": "Admin",
        "operations": [
            "All"
        ],
        "level": "Eligibility",
        "targetObjects": null,
        "inheritableSettings": null,
        "enforcedSettings": null
        }
        }
        ],
          "level": "Assignment"
            }
        }
VERBOSE: requested URI : https://management.azure.com//subscriptions//providers/Microsoft.Authorization/roleManagementPolicies//?api-
version=2020-10-01 ; method : PATCH
VERBOSE: >> Getting access token
WARNING: Upcoming breaking changes in the cmdlet 'Get-AzAccessToken' :
The Token property of the output type will be changed from String to SecureString. Add the [-AsSecureString] switch 
to avoid the impact of this upcoming breaking change.
- The change is expected to take effect in Az version : '13.0.0'
- The change is expected to take effect in Az.Accounts version : '4.0.0'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other inform
ation on breaking changes in Azure PowerShell.
VERBOSE: MyCatch function called
An exception occured: The remote server returned an error: (400) Bad Request.
 
Details: {"error":{"code":"InputPolicyNotFound","message":"Policy is not found."}} 
Position: At C:\Program Files\WindowsPowerShell\Modules\EasyPIM\1.6.6\EasyPIM.psm1:894 char:25
+ ... $response = Invoke-RestMethod -Uri $restUri -Method $method -Headers  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
VERBOSE: MyCatch function called
An exception occured: Error, script did not terminate gracefuly
 
Details:  
Position: At C:\Program Files\WindowsPowerShell\Modules\EasyPIM\1.6.6\EasyPIM.psm1:1127 char:5
+     throw "Error, script did not terminate gracefuly" #fix issue #40
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error, script did not terminate gracefuly
At C:\Program Files\WindowsPowerShell\Modules\EasyPIM\1.6.6\EasyPIM.psm1:1127 char:5
+     throw "Error, script did not terminate gracefuly" #fix issue #40
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error, script d...inate gracefuly:String) [], RuntimeException
    + FullyQualifiedErrorId : Error, script did not terminate gracefuly

**Comment by Mansars** [comment]
This appears to be being caused by something on my end regarding resource groups or roles. Ill update when I further investigate with Loic

**Comment by kayasax** [comment]
@Mansars  I think the subscription ID is missing here

VERBOSE: requested URI : https://management.azure.com//subscriptions//providers/Microsoft.Authorization/roleManagementPolicies//?api-
version=2020-10-01 ; method : PATCH

**Comment by Mansars** [comment]
Yeah I removed it prior to posting
