### ISSUE TITLE
Set-PIMAzureResourcePolicy fails with error 'Error, script did not terminate gracefuly'

### ISSUE THREAD

**Issue by DonKoning** [kayasax/EasyPIM#71]
Trying EasyPIM for the first time.

Logged on as Entra ID Global Admin and Owner on Azure subscription. If I run from terminal:

Set-PIMAzureResourcePolicy -ActivationRequirement "Justification" -subscriptionID <id>  -rolename "Security Reader" -ActivationDuration "PT2H" -tenantID <tenantId> -AllowPermanentEligibility $true -ApprovalRequired $false

I get:

An exception occured: You cannot call a method on a null-valued expression.
Details:
Position: EasyPIM\1.7.1\EasyPIM.psm1:1632 char:22
+         $Approvers | ForEach-Object {
+                      ~~~~~~~~~~~~~~~~
An exception occured: Error, script did not terminate gracefuly
Details:
Position: EasyPIM\1.7.1\EasyPIM.psm1:1143 char:5
+     throw "Error, script did not terminate gracefuly" #fix issue #40
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exception: Error, script did not terminate gracefuly

After removing '-ApprovalRequired $false' I get slightly different error message (timeout):

An exception occured: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

Details:
Position: EasyPIM\1.7.1\EasyPIM.psm1:910 char:23
+ …           $response=Invoke-AZRestMethod -Method $method -Uri $restURI
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
An exception occured: Error, script did not terminate gracefuly

Details:
Position: EasyPIM\1.7.1\EasyPIM.psm1:1143 char:5
+     throw "Error, script did not terminate gracefuly" #fix issue #40
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
An exception occured: Error, script did not terminate gracefuly

Details:
Position: EasyPIM\1.7.1\EasyPIM.psm1:1143 char:5
+     throw "Error, script did not terminate gracefuly" #fix issue #40
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exception: Error, script did not terminate gracefuly

If I rerun this last command, it apparently works: 'Success, policy updated', but keeps failing when I re-add '-ApprovalRequired $false'. 

Is it a case of PEBKAC or is it issue with script?

**Comment by kayasax** [comment]
thank you @DonKoning for reporting this issue, I confirm I have the same behavior, will look at it.
