### ISSUE TITLE
EasyPIM support for Management Groups

### ISSUE THREAD

**Issue by DonKoning** [kayasax/EasyPIM#72]
If I try 'get-PIMAzureResourcePolicy' or 'Set-PIMAzureResourcePolicy' with the - scope parameter "/providers/Microsoft.Management/managementgroups/alz", it fails directly with this error message:

An exception occured: Cannot index into a null array.

Details:
Position: At EasyPIM\1.7.1\EasyPIM.psm1:878 char:9
+         $script:subscriptionID=[regex]::Matches($restURI,".*\/subscri …
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
An exception occured: Error, script did not terminate gracefuly

Details:
Position: At EasyPIM\1.7.1\EasyPIM.psm1:1143 char:5
+     throw "Error, script did not terminate gracefuly" #fix issue #40
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
An exception occured: Error, script did not terminate gracefuly

Details:
Position: At EasyPIM\1.7.1\EasyPIM.psm1:1143 char:5
+     throw "Error, script did not terminate gracefuly" #fix issue #40
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exception: Error, script did not terminate gracefuly

**Comment by kayasax** [comment]
Is there an assignement defined at this scope for the role you selected?
From my test it fails when there is no assignment
![image](https://github.com/user-attachments/assets/c8a4a25e-373a-4156-9dcf-dc6c0802523c)

but it's OK when there are some
![image](https://github.com/user-attachments/assets/a9798e1d-b91b-4424-b909-6b96a6f2d09c)

**Comment by kayasax** [comment]
this is fixed in V1.7.2 thanks!
